# base config: dinov2/configs/train/vitl14.yaml
compute_precision:
  grad_scaler: true
  teacher:
    supervised_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    supervised_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    domain_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32

ibot:
  separate_head: true
  #head_n_prototypes: 131072
data_transform: "default"
train:
  batch_size_per_gpu: 64 #vitg 26+, vitl: 56, vits:152, vitb:120 for 8 node
  num_workers: 25
  OFFICIAL_EPOCH_LENGTH: 500  # 1250
  dataset_path_sup: CytologiaSup:df_path=/home/aih/manon.chossegros/Challenge/src/dinov2/dinobloom_dataset_train_and_test.csv:shuffle=1
  dataset_path_sup_val: CytologiaSup:df_path=/home/aih/manon.chossegros/Challenge/src/dinov2/dinobloom_dataset_eval_reduced.csv:shuffle=1
  dataset_path_unsup: CytologiaUnSup:df_path=/home/aih/manon.chossegros/Challenge/src/dinov2/dinobloom_dataset_train_and_test.csv:shuffle=1
  centering: sinkhorn_knopp
  n_classes: 27

  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 0  # for distributed training
  num_register_tokens: 0  # 0 for no register tokens

teacher:
  momentum_teacher: 0.994
optim:
  epochs: 200  # 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 20  # 80
  layerwise_decay: 1.0


evaluation:
  eval_period_iterations: 1000

# adapt to model architecture
# ---------------------------
# config for vit
# "dinov2_vits14","dinov2_vitb14","dinov2_vitl14","dinov2_vitg14"
student:
  arch: dinov2_vitl14
  patch_size: 14
crops:
  global_crops_scale:
  - 0.32 #0.32 default
  - 1.0
  local_crops_size: 98
  local_crops_number: 1
dino:
  head_bottleneck_dim: 384 #vits: 256, vitl: 384 
  smooth_rank_loss_weight: 0.0
  koleo_loss_weight: 0.0

supervised:
  loss_weight: 1.0
  n_classes: 27

n_levels: 4
label_dict: 
  # --- harmonized labels ---
  basophil: [3,1,0,-1]
  eosinophil: [3,1,2,0]
  erythroblast: [0,1,-1,-1]
  lymphocyte_typical: [2,1,1,0]
  lymphocyte: [2,1,-1,-1]
  metamyelocyte: [3,0,3,-1]
  monocyte: [1,1,0,-1]
  myeloblast: [3,0,0,-1]
  myelocyte: [3,0,2,-1]
  neutrophil_band: [3,1,1,0]
  neutrophil_segmented: [3,1,1,1]
  promyelocyte: [3,0,1,0]
  lymphoblast: [2,0,1,-1]
  platelet: [6,0,-1,-1]

  # --- Matek non-harmonized ---#
  BAS: [3,1,0,-1]
  EBO: [0,1,-1,-1]
  EOS: [3,1,2,0]
  KSC: [4,0,-1,-1]
  LYT: [2,1,1,0]
  MMZ: [3,0,3,-1] #metamyelocyte
  MON: [1,1,0,-1]
  MYB: [3,0,2,-1] #yes, its myelocyte!
  MYO: [3,0,0,-1] #myeloblast
  NGB: [3,1,1,0]
  NGS: [3,1,1,1]
  PMO: [3,0,1,0]
  PMB: [3,0,1,2] # promyelocyte (bilobed)
  MOB: [1,0,0,-1] #Monoblast 
  LYA: [2,1,2,0]

  # --- Marr_Mll non-harmonized ---#
  01-NORMO: [0,1,-1,-1]
  1-Normo: [0,1,-1,-1]
  05-MONO: [1,1,0,-1]
  5-MONO: [1,1,0,-1]
  09-BASO: [3,1,0,-1]
  11-STAB: [3,1,1,0]
  13-MYBL: [3,0,0,-1]
  15-SEG: [3,1,1,1]
  17-Kernschatten: [4,0,-1,-1]
  19-MYEL: [3,0,2,-1]
  21-Haarzelle: [2,1,0,-1]
  10-EOS: [3,1,2,0]
  14-LYMPH-typ: [2,1,1,0]
  16-PLZ: [2,1,1,-1]
  18-PMYEL: [3,0,1,0]
  20-Meta: [3,0,3,-1]
  20-META: [3,0,3,-1]
  9-BASO: [3,1,0,-1]
  #22-Atyp-PMYEL: atypical promyelocyte
  12-LYMPH-reaktiv: [2,1,2,1]
  08-LYMPH-neo: [2,1,4,-1]
  04-LGL: [2,1,3,-1]

  # --- Raabin WBC / Warthog labels /KRD_WBC/LISC ---
  Eosinophil: [3,1,2,0]
  Lymphocyte: [2,1,1,0]
  Lymphocyte-1: [2,1,1,0]
  Monocyte: [1,1,0,-1]
  Neutrophil: [3,1,1,-1] # 8/9 > hierarchical loss term
  Basophil: [3,1,0,-1]
 
  ## extras 
  basophile: [3,1,0,-1]
  eosinophile: [3,1,2,0]
  

  # --- Bone marrow labels ---
  ABE: [3,1,2,1]  # (Abnormal eosinophils)
  # ART (Artefacts)
  #BAS: 0 duplicate # (Basophils)
  BLA: [5,0,-1,-1] # (Blasts)
  #EBO: 2 duplicate # (Erythroblasts)
  #EOS: 1  duplicate # (Eosinophils)
  FGC: [3,0,1,1] # (Faggot cells)
  HAC: [2,1,0,-1] #(Hairy cells)
  #KSC:  # (Smudge cells)
  LYI: [2,0,0,-1] #(Immature lymphocytes)
  #LYT: 3  duplicate # (Lymphocytes)
  #MMZ: 4  dupl # (Metamyelocytes)
  #MON: 5  dupl # (Monocytes)
  #MYB: 6 dupl  # (Myelocytes)
  #NGB: 8  dupl # (Band neutrophils)
  #NGS: 9 dupl # (Segmented neutrophils)
  # NIF (Not identifiable)
  # OTH (Other cells)
  PEB: [0,0,-1,-1] # (Proerythoblasts)
  PLM: [2,1,1,1] # (Plasma cells)
  #PMO: 10 # dupl (Promyelocytes)

# ---------------------------
# config for vim_tiny
#student:
#  arch: vim_tiny
#  patch_size: 16
#crops:
#  local_crops_size: 96
#dino:
#  head_bottleneck_dim: 256
