# base config: dinov2/configs/train/vitl14.yaml
compute_precision:
  grad_scaler: true
  teacher:
    supervised_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    supervised_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    domain_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32

ibot:
  separate_head: true
  #head_n_prototypes: 131072
data_transform: default
train:
  batch_size_per_gpu: 64 #vitg 26+, vitl: 56, vits:152, vitb:120 for 8 node
  num_workers: 15
  OFFICIAL_EPOCH_LENGTH: 500  # 1250
  dataset_path: HemaStandardDataset:root=/mnt/ceph_vol/dinov2/train_files:shuffle=1
  centering: sinkhorn_knopp

  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 0  # for distributed training
  num_register_tokens: 0  # 0 for no register tokens

teacher:
  momentum_teacher: 0.994
optim:
  epochs: 200  # 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 20  # 80
  layerwise_decay: 1.0

evaluation:
  eval_period_iterations: 1000
domain:
  loss_weight: 0.1
  criterion: CrossEntropy
  head: MLP
  n_classes: 2
  label_dict:
    20-014_K11_Movat: 0
    20-014_K11_EvG: 1
label_dict: 
  # --- harmonized labels ---
  basophil: 0
  eosinophil: 1
  erythroblast: 2
  lymphocyte_typical: 3
  metamyelocyte: 4
  monocyte: 5
  myeloblast: 6
  myelocyte: 7
  neutrophil_band: 8
  neutrophil_segmented: 9
  promyelocyte: 10
  # --- Raabin WBC / Warthog labels ---
  Eosinophil: 1
  Lymphocyte: 3 
  Lymphocyte-1: 3 
  Monocyte: 5 
  # Neutrophil: 8/9 > hierarchical loss term
  Basophil: 0
  # --- Bone marrow labels ---
  ABE: 1  # (Abnormal eosinophils)
  # ART (Artefacts)
  BAS: 0  # (Basophils)
  # BLA (Blasts)
  EBO: 2  # (Erythroblasts)
  EOS: 1  # (Eosinophils)
  # FGC (Faggot cells)
  # HAC (Hairy cells)
  # KSC (Sudge cells)
  # LYI (Immature lymphocytes)
  LYT: 3  # (Lymphocytes)
  MMZ: 4  # (Metamyelocytes)
  MON: 5  # (Monocytes)
  MYB: 6  # (Myelocytes)
  NGB: 8  # (Band neutrophils)
  NGS: 9  # (Segmented neutrophils)
  # NIF (Not identifiable)
  # OTH (Other cells)
  # PEB (Proerythoblasts)
  # PLM (Plasma cells)
  PMO: 10 #  (Promyelocytes)

supervised:
  loss_weight: 0.1
  n_classes: 11
  criterion: CrossEntropy  # CrossEntropy or SupConLoss
  head: MLP  # MLP or DINOHead
  wait_iter: -1  # 0
  dicts: [
    {head: "MLP", n_classes: 11, losses: ["SupConLoss", "CrossEntropy"]}
  ]

# adapt to model architecture
# ---------------------------
# config for vit
# "dinov2_vits14","dinov2_vitb14","dinov2_vitl14","dinov2_vitg14"
student:
  arch: dinov2_vits14
  patch_size: 14
crops:
  global_crops_scale:
  - 0.32 #0.32 default
  - 1.0
  local_crops_size: 98
  local_crops_number: 1
dino:
  head_bottleneck_dim: 256 #vits: 256, vitl: 384 
  smooth_rank_loss_weight: 0.0

# ---------------------------
# config for vim_tiny
#student:
#  arch: vim_tiny
#  patch_size: 16
#crops:
#  local_crops_size: 96
#dino:
#  head_bottleneck_dim: 256
