CUDA_VISIBLE_DEVICES=1 python generate_images.py \
  --mixed_precision="bf16" \
  --path_to_model_dir="/mnt/bulk-uranus/janniehues/dino_bloom/new/dino_bloom_anal/diffusers/model_0" \
  --batch_size=32 \
  --num_inference_steps=100 --num_images_per_prompt=32 \
  --prompts="Histopathological image of a single cell of type lymphocyte. The image is from site LDWBC" \
  --output_dir="outputs_model_0" 
  # --validation_prompts 
    "Histopathological image of a single cell of type lymphocyte. The image is from site LDWBC" 
    "Histopathological image of a single cell of type eosinophil. The image is from site LDWBC" 
    "Histopathological image of a single cell of type monocyte. The image is from site LDWBC" 
    "Histopathological image of a single cell of type neutrophil. The image is from site LDWBC" 
    "Histopathological image of a single cell of type basophil. The image is from site LDWBC" 
    "Histopathological image of a single cell of type neutrophil segmented. The image is from site Bodzas" 
    "Histopathological image of a single cell of type lymphocyte. The image is from site Bodzas" 
    "Histopathological image of a single cell of type eosinophil. The image is from site Bodzas" 
    "Histopathological image of a single cell of type monocyte. The image is from site Bodzas" 
    "Histopathological image of a single cell of type basophil. The image is from site Bodzas" 
    "Histopathological image of a single cell of type lymphoblast. The image is from site Bodzas" 
    "Histopathological image of a single cell of type neutrophil band. The image is from site Bodzas" 
    "Histopathological image of a single cell of type myeloblast. The image is from site Bodzas" 
    "Histopathological image of a single cell of type normoblast. The image is from site Bodzas" 
    "Histopathological image of a single cell of type metamyelocyte. The image is from site beluga" 
    "Histopathological image of a single cell of type miscellaneous. The image is from site beluga" 
    "Histopathological image of a single cell of type neutrophil segmented. The image is from site beluga" 
    "Histopathological image of a single cell of type lymphocyte reactive. The image is from site beluga" 
    "Histopathological image of a single cell of type monocyte. The image is from site beluga" 
    "Histopathological image of a single cell of type neutrophil band. The image is from site beluga" 
    "Histopathological image of a single cell of type eosinophil. The image is from site beluga" 
    "Histopathological image of a single cell of type myeloblast. The image is from site beluga" 
    "Histopathological image of a single cell of type basophil. The image is from site beluga" 
    "Histopathological image of a single cell of type promyelocyte atypical. The image is from site beluga" 
    "Histopathological image of a single cell of type lymphocyte. The image is from site beluga" 
    "Histopathological image of a single cell of type mononucleose. The image is from site beluga" 
    "Histopathological image of a single cell of type lymphocyte neoplastic. The image is from site beluga" 
    "Histopathological image of a single cell of type lymphocyte large granular. The image is from site beluga" 
    "Histopathological image of a single cell of type smudge cell. The image is from site beluga" 
    "Histopathological image of a single cell of type plasma cell. The image is from site beluga" 
    "Histopathological image of a single cell of type normoblast. The image is from site beluga" 
    "Histopathological image of a single cell of type promyelocyte. The image is from site beluga" 
    "Histopathological image of a single cell of type myelocyte. The image is from site beluga" 
    "Histopathological image of a single cell of type hairy cell. The image is from site beluga" 
    "Histopathological image of a single cell of type eosinophil. The image is from site Marr" 
    "Histopathological image of a single cell of type monoblast. The image is from site Marr" 
    "Histopathological image of a single cell of type erythroblast. The image is from site Marr" 
    "Histopathological image of a single cell of type neutrophil segmented. The image is from site Marr" 
    "Histopathological image of a single cell of type lymphocyte. The image is from site Marr" 
    "Histopathological image of a single cell of type promyelocyte. The image is from site Marr" 
    "Histopathological image of a single cell of type metamyelocyte. The image is from site Marr" 
    "Histopathological image of a single cell of type myeloblast. The image is from site Marr" 
    "Histopathological image of a single cell of type myelocyte. The image is from site Marr" 
    "Histopathological image of a single cell of type smudge. The image is from site Marr" 
    "Histopathological image of a single cell of type neutrophil band. The image is from site Marr" 
    "Histopathological image of a single cell of type basophil. The image is from site Marr" 
    "Histopathological image of a single cell of type promyelocyte bilobed. The image is from site Marr" 
    "Histopathological image of a single cell of type monocyte. The image is from site Marr" 
    "Histopathological image of a single cell of type lymphocyte atypical. The image is from site Marr" 
    "Histopathological image of a single cell of type plasma cell. The image is from site Matek" 
    "Histopathological image of a single cell of type basophil. The image is from site Matek" 
    "Histopathological image of a single cell of type neutrophil band. The image is from site Matek" 
    "Histopathological image of a single cell of type monocyte. The image is from site Matek" 
    "Histopathological image of a single cell of type hairy cell. The image is from site Matek" 
    "Histopathological image of a single cell of type promyelocyte. The image is from site Matek" 
    "Histopathological image of a single cell of type neutrophil segmented. The image is from site Matek" 
    "Histopathological image of a single cell of type normoblast. The image is from site Matek" 
    "Histopathological image of a single cell of type lymphocyte large granular. The image is from site Matek" 
    "Histopathological image of a single cell of type myeloblast. The image is from site Matek" 
    "Histopathological image of a single cell of type smudge cell. The image is from site Matek" 
    "Histopathological image of a single cell of type lymphocyte. The image is from site Matek" 
    "Histopathological image of a single cell of type myelocyte. The image is from site Matek" 
    "Histopathological image of a single cell of type promyelocyte atypical. The image is from site Matek" 
    "Histopathological image of a single cell of type metamyelocyte. The image is from site Matek" 
    "Histopathological image of a single cell of type lymphocyte neoplastic. The image is from site Matek" 
    "Histopathological image of a single cell of type lymphocyte reactive. The image is from site Matek" 
    "Histopathological image of a single cell of type eosinophil. The image is from site Matek"
##   --resume_from_checkpoint="/mnt/bulk/janniehues/dino_bloom/new/dino_bloom_anal/diffusers/dino_bloom/checkpoint-4000" \
##    #--max_train_steps=15000 \
##   --lr_scheduler="constant" --lr_warmup_steps=0 \